version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=anon_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=anon_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_network

  anonymization_service:
    build: ./anonymization
    container_name: anonymization_service
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://anon_user:securepassword@db/anon_db
    networks:
      - internal_network

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - anonymization_service
    networks:
      - internal_network
      - external_network



networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge

volumes:
  db_data:
